name: Daily News Update

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 자동 실행
  workflow_dispatch: # 내가 원할 때 수동 실행 가능하게 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run update script
        run: python update_news.py
      - name: Commit and Push
        run: |
          git config --global user.name "ysk9071"
          git config --global user.email "ysk9071@gmail.com"
          git add index.html
          git commit -m "Auto-update News [skip ci]" || echo "No changes to commit"
          git push
